version: '3'
services:
  web:
    ports:
      - "8000"
    env_file:
      - .env.staging
  worker:
    env_file:
      - .env.staging
  proxy:
    image: svenstaro/ssl-proxy
    command: ["-from", "0.0.0.0:443", "-to", "web:8000"]
    ports:
      - "443:443"
