version: '3'
services:
  web:
    ports:
      - "8000"
    env_file:
      - .env.staging
  worker:
    env_file:
      - .env.staging
  proxy:
    image: caddy:2-alpine
    command: "caddy reverse-proxy --from ${PULLPREVIEW_PUBLIC_DNS} --to web:8000"
    restart: unless-stopped
    depends_on:
      - web
    networks:
      - frontend
    ports:
      - "443:443"
      - "80:80"
