# https://semaphoreci.com/community/tutorials/dockerizing-a-ruby-on-rails-application
postgres:
  image: postgres:9.4.5
  environment:
    POSTGRES_USER: app
    POSTGRES_PASSWORD: p4ssw0rd
    POSTGRES_DB: app
  expose:
    - "5432"
  ports:
    - '15432:5432'
  volumes:
    - ./export/db:/var/lib/postgresql/data
  memory: 64

redis:
  image: redis:3.0.5
  expose:
    - "6379"
  ports:
    - '16379:6379'
  memory: 64

web:
  build: .
  links:
    - postgres
    - redis
  volumes:
    - .:/app
  ports:
    - '80:8000'
  env_file:
    - .env.pullpreview
  memory: 512

worker:
  build: .
  command: ./proc/worker
  links:
    - postgres
    - redis
  volumes:
    - .:/app
  env_file:
    - .env.pullpreview
  memory: 384
